//! Tailang 本地代码生成后端
//!
//! 当前阶段的目标不是一次性实现完整 LLVM 编译器，而是先定义清晰、可测试、
//! 可扩展的 Rust 编译后端接口：遗留 `.tai` JSON 快照 -> Rust 源码 -> 系统 Rust 编译器。

use crate::tai::{TaiCodeBlock, TaiFile, TaiTranslator};
use crate::tai_ast::{TaiFunctionDecl, TaiProgram, TaiVarDecl};
use crate::tai_exec::{
    parse_native_tai_exec, render_native_tai_exec_to_rust, render_native_tai_expr_to_rust,
};
use crate::tai_parser::TaiParser;
use std::path::{Path, PathBuf};
use std::process::Command;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RustCodegenOutput {
    pub rust_source: String,
    pub entry_function: String,
}

pub struct CodeGenerator;

impl CodeGenerator {
    pub fn new() -> Self {
        Self
    }

    pub fn generate_rust_source(&self, tai: &TaiFile) -> Result<RustCodegenOutput, String> {
        let mut source = String::new();
        source.push_str("// Generated by Tailang compiler\n");
        source.push_str("// Native backend implemented in Rust\n\n");

        for item in &tai.unresolved_items {
            source.push_str(&format!("// unresolved {}: {}\n", item.kind, item.description));
        }
        if !tai.unresolved_items.is_empty() {
            source.push('\n');
        }

        let rust_blocks = filter_code_blocks(&tai.code_blocks, "rust");
        for block in rust_blocks {
            source.push_str(block.code.trim());
            source.push_str("\n\n");
        }

        if !contains_main_function(&source) {
            source.push_str("fn tailang_main() {\n");

            let body = render_fallback_rust_body(tai);
            if body.is_empty() {
                source.push_str("    // No executable statements were inferred from .tai yet.\n");
            } else {
                for line in body {
                    source.push_str("    ");
                    source.push_str(&line);
                    source.push('\n');
                }
            }

            source.push_str("}\n\n");
            source.push_str("fn main() {\n");
            source.push_str("    tailang_main();\n");
            source.push_str("}\n");
        }

        Ok(RustCodegenOutput {
            rust_source: source,
            entry_function: "main".to_string(),
        })
    }

    pub fn generate_rust_from_program(
        &self,
        program: &TaiProgram,
    ) -> Result<RustCodegenOutput, String> {
        let mut source = String::new();
        source.push_str("// Generated by Tailang compiler\n");
        source.push_str("// Native backend implemented in Rust\n");
        source.push_str("use std::collections::BTreeMap;\n\n");

        for field in &program.meta {
            source.push_str(&format!("// meta {} = {:?}\n", field.key, field.value));
        }
        if let Some(target) = &program.target {
            source.push_str(&format!("// target {}\n", target));
        }
        if !program.meta.is_empty() || program.target.is_some() {
            source.push('\n');
        }

        for module in &program.modules {
            source.push_str(&format!("mod {} {{\n", sanitize_rust_identifier(&module.name)));
            source.push_str("    #[allow(unused_imports)]\n");
            source.push_str("    use super::*;\n\n");

            for global in &module.globals {
                source.push_str("    ");
                source.push_str(&render_module_global(global)?);
                source.push('\n');
            }
            if !module.globals.is_empty() {
                source.push('\n');
            }

            for function in &module.functions {
                let params = function
                    .param_decls
                    .iter()
                    .map(render_param_decl)
                    .collect::<Result<Vec<_>, _>>()?
                    .join(", ");
                let return_type = map_function_return_type(function);

                source.push_str(&format!(
                    "    pub fn {}({}) -> {} {{\n",
                    sanitize_rust_identifier(&function.name),
                    params,
                    return_type
                ));

                if let Some(doc) = &function.doc {
                    source.push_str(&format!("        // doc: {}\n", doc));
                }

                for validation in &function.validations {
                    source.push_str(&format!("        println!({:?});\n", validation));
                }
                if !function.validations.is_empty() {
                    source.push('\n');
                }

                for local in &function.locals {
                    source.push_str("        ");
                    source.push_str(&render_local_decl(local)?);
                    source.push('\n');
                }
                if !function.locals.is_empty() {
                    source.push('\n');
                }

                if let Some(implementation) = &function.implementation {
                    let implementation_body =
                        lower_implementation_to_rust(function, implementation)?;
                    for line in implementation_body.lines() {
                        if line.trim().is_empty() {
                            source.push('\n');
                            continue;
                        }
                        source.push_str("        ");
                        source.push_str(line);
                        source.push('\n');
                    }
                }

                for code in &function.code_blocks {
                    if code.language.eq_ignore_ascii_case("rust") {
                        for line in code.body.lines() {
                            source.push_str("        ");
                            source.push_str(line);
                            source.push('\n');
                        }
                    } else {
                        source.push_str(&format!(
                            "        // code block [{}] preserved for later lowering\n",
                            code.language
                        ));
                    }
                }

                source.push_str("    }\n\n");
            }

            source.push_str("}\n\n");
        }

        if !contains_main_function(&source) {
            source.push_str("fn main() {\n");
            for module in &program.modules {
                for global in &module.globals {
                    source.push_str(&format!(
                        "    let _ = {}::{}();\n",
                        sanitize_rust_identifier(&module.name),
                        global_initializer_name(&global.name)
                    ));
                }
                for function in &module.functions {
                    let call_args = function
                        .param_decls
                        .iter()
                        .map(default_rust_argument_for_decl)
                        .collect::<Result<Vec<_>, _>>()?
                        .join(", ");
                    source.push_str(&format!(
                        "    let _ = {}::{}({});\n",
                        sanitize_rust_identifier(&module.name),
                        sanitize_rust_identifier(&function.name),
                        call_args
                    ));
                }
            }

            for unresolved in &program.unresolved {
                source.push_str(&format!(
                    "    println!({:?});\n",
                    format!("unresolved {}: {}", unresolved.kind, unresolved.description)
                ));
            }

            source.push_str("}\n");
        }

        Ok(RustCodegenOutput {
            rust_source: source,
            entry_function: "main".to_string(),
        })
    }
}

impl Default for CodeGenerator {
    fn default() -> Self {
        Self::new()
    }
}

pub fn generate_rust_from_tai_snapshot(tai_json: &str) -> Result<RustCodegenOutput, String> {
    let translator = TaiTranslator::new();
    let tai = translator.deserialize(tai_json)?;
    CodeGenerator::new().generate_rust_source(&tai)
}

pub fn generate_rust_from_tai_source(tai_source: &str) -> Result<RustCodegenOutput, String> {
    let program = TaiParser::from_source(tai_source)
        .map_err(|err| format!("parse .tai source failed at {}: {}", err.offset, err.message))?;
    CodeGenerator::new().generate_rust_from_program(&program)
}

pub fn compile_tai_snapshot_to_executable(tai_json: &str, output: &str) -> Result<(), String> {
    let generated = generate_rust_from_tai_snapshot(tai_json)?;
    compile_rust_output(&generated, output)
}

pub fn compile_tai_source_to_executable(tai_source: &str, output: &str) -> Result<(), String> {
    let generated = generate_rust_from_tai_source(tai_source)?;
    compile_rust_output(&generated, output)
}

fn compile_rust_output(generated: &RustCodegenOutput, output: &str) -> Result<(), String> {
    let output_path = PathBuf::from(output);
    let rust_path = rust_source_path(&output_path);
    if let Some(parent) = rust_path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| format!("创建输出目录失败：{}", e))?;
    }

    std::fs::write(&rust_path, &generated.rust_source)
        .map_err(|e| format!("写入 Rust 源文件失败：{}", e))?;

    let rustc = std::env::var("TAILANG_RUSTC").unwrap_or_else(|_| "rustc".to_string());
    let status = Command::new(&rustc)
        .arg(&rust_path)
        .arg("-o")
        .arg(&output_path)
        .status()
        .map_err(|e| format!("调用 rustc 失败：{}", e))?;

    if !status.success() {
        return Err(format!("rustc 编译失败，退出码：{:?}", status.code()));
    }

    Ok(())
}

fn rust_source_path(output: &Path) -> PathBuf {
    let mut path = output.to_path_buf();
    path.set_extension("rs");
    path
}

fn filter_code_blocks<'a>(blocks: &'a [TaiCodeBlock], language: &str) -> Vec<&'a TaiCodeBlock> {
    blocks
        .iter()
        .filter(|block| block.language.trim().eq_ignore_ascii_case(language))
        .collect()
}

fn contains_main_function(source: &str) -> bool {
    source.contains("fn main(") || source.contains("fn main ()")
}

fn sanitize_rust_identifier(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for (idx, ch) in input.chars().enumerate() {
        let valid = ch == '_' || ch.is_alphanumeric();
        if !valid {
            out.push('_');
            continue;
        }
        if idx == 0 && ch.is_ascii_digit() {
            out.push('_');
        }
        out.push(ch);
    }

    if out.is_empty() {
        "generated".to_string()
    } else {
        out
    }
}

fn render_module_global(global: &TaiVarDecl) -> Result<String, String> {
    Ok(format!(
        "pub fn {}() -> {} {{ {} }}",
        global_initializer_name(&global.name),
        map_decl_type(global)?,
        render_decl_initializer(global)?
    ))
}

fn render_param_decl(param: &TaiVarDecl) -> Result<String, String> {
    Ok(format!(
        "{}: {}",
        sanitize_rust_identifier(&param.name),
        map_decl_type(param)?
    ))
}

fn render_local_decl(local: &TaiVarDecl) -> Result<String, String> {
    let name = sanitize_rust_identifier(&local.name);
    let ty = map_decl_type(local)?;
    match &local.value {
        Some(_) => Ok(format!(
            "let mut {}: {} = {};",
            name,
            ty,
            render_decl_initializer(local)?
        )),
        None => Ok(format!("let mut {}: {} = {};", name, ty, default_value_for_type(&ty))),
    }
}

fn map_function_return_type(function: &TaiFunctionDecl) -> String {
    match function.return_type.as_deref() {
        Some(value) => map_tai_type_to_rust(value),
        None => "()".to_string(),
    }
}

fn map_decl_type(decl: &TaiVarDecl) -> Result<String, String> {
    if let Some(ty) = decl.ty.as_deref() {
        Ok(map_tai_type_to_rust(ty))
    } else if let Some(value) = decl.value.as_deref() {
        infer_rust_type_from_value(value)
    } else {
        Ok("String".to_string())
    }
}

fn map_tai_type_to_rust(ty: &str) -> String {
    match ty.trim() {
        "" => "()".to_string(),
        "文本型" => "String".to_string(),
        "整数型" => "i64".to_string(),
        "小数型" | "实数型" => "f64".to_string(),
        "逻辑型" => "bool".to_string(),
        "任意型" => "String".to_string(),
        "整数数组" => "Vec<i64>".to_string(),
        "文本数组" => "Vec<String>".to_string(),
        "映射型" => "BTreeMap<String, String>".to_string(),
        other => sanitize_rust_identifier(other),
    }
}

fn infer_rust_type_from_value(value: &str) -> Result<String, String> {
    let trimmed = value.trim();
    if trimmed.starts_with('"') && trimmed.ends_with('"') {
        return Ok("String".to_string());
    }
    if matches!(trimmed, ".真" | ".假" | "真" | "假") {
        return Ok("bool".to_string());
    }
    if trimmed.parse::<i64>().is_ok() {
        return Ok("i64".to_string());
    }
    if trimmed.parse::<f64>().is_ok() {
        return Ok("f64".to_string());
    }
    if trimmed.starts_with('[') {
        return Ok("Vec<String>".to_string());
    }
    if trimmed.starts_with('{') {
        return Ok("BTreeMap<String, String>".to_string());
    }
    Ok("String".to_string())
}

fn render_decl_initializer(decl: &TaiVarDecl) -> Result<String, String> {
    let ty = map_decl_type(decl)?;
    if let Some(value) = &decl.value {
        return render_value_for_type(value, &ty);
    }
    Ok(default_value_for_type(&ty).to_string())
}

fn render_value_for_type(value: &str, ty: &str) -> Result<String, String> {
    let raw = render_native_tai_expr_to_rust(value)
        .map_err(|err| format!("初始化表达式解析失败：{}", err.message))?;
    match ty {
        "String" if raw.starts_with('"') => Ok(format!("{}.to_string()", raw)),
        "String" if matches!(raw.as_str(), "true" | "false") => Ok(format!("{}.to_string()", raw)),
        "String" if raw.chars().all(|ch| ch.is_ascii_digit()) => Ok(format!("{}.to_string()", raw)),
        _ => Ok(raw),
    }
}

fn default_value_for_type(ty: &str) -> &'static str {
    match ty {
        "String" => "String::new()",
        "i64" => "0",
        "f64" => "0.0",
        "bool" => "false",
        "Vec<i64>" => "Vec::new()",
        "Vec<String>" => "Vec::new()",
        "BTreeMap<String, String>" => "BTreeMap::new()",
        _ => "Default::default()",
    }
}

fn default_rust_argument_for_decl(param: &TaiVarDecl) -> Result<String, String> {
    let ty = map_decl_type(param)?;
    Ok(default_value_for_type(&ty).to_string())
}

fn global_initializer_name(input: &str) -> String {
    format!("{}_初始化", sanitize_rust_identifier(input))
}

fn render_fallback_rust_body(tai: &TaiFile) -> Vec<String> {
    let mut lines = Vec::new();
    let mut seen = std::collections::BTreeSet::new();

    let mut emit_quoted = |input: &str| {
        for value in collect_quoted_strings(input) {
            if seen.insert(value.clone()) {
                lines.push(format!("println!({:?});", value));
            }
        }
    };

    for module in &tai.modules {
        emit_quoted(&module.description);
        for function in &module.functions {
            emit_quoted(&function.description);
            for validation in &function.validations {
                emit_quoted(validation);
            }
        }
    }

    for block in &tai.code_blocks {
        if block.language.trim().eq_ignore_ascii_case("rust") {
            continue;
        }
        emit_quoted(&block.code);
    }

    if !tai.unresolved_items.is_empty() {
        lines.push("println!(\"Warning: unresolved Tailang items remain.\");".to_string());
    }

    lines
}

fn collect_quoted_strings(input: &str) -> Vec<String> {
    let mut values = Vec::new();
    let chars: Vec<char> = input.chars().collect();
    let mut idx = 0usize;

    while idx < chars.len() {
        let quote = chars[idx];
        if quote != '"' && quote != '\'' {
            idx += 1;
            continue;
        }

        idx += 1;
        let start = idx;
        while idx < chars.len() && chars[idx] != quote {
            if chars[idx] == '\\' {
                idx += 1;
            }
            idx += 1;
        }

        if idx <= chars.len() {
            let value: String = chars[start..idx.min(chars.len())].iter().collect();
            if !value.trim().is_empty() {
                values.push(value);
            }
        }

        idx += 1;
    }

    values
}

fn lower_implementation_to_rust(
    _function: &TaiFunctionDecl,
    implementation: &str,
) -> Result<String, String> {
    let statements = parse_native_tai_exec(implementation)
        .map_err(|err| format!("原生 .tai 执行语法解析失败：{}", err.message))?;
    Ok(render_native_tai_exec_to_rust(&statements))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_tai() -> TaiFile {
        TaiFile {
            version: "0.1.0".to_string(),
            source: crate::tai::TaiSource {
                provider: "compiler".to_string(),
                model: "test".to_string(),
                temperature: "0".to_string(),
            },
            modules: vec![crate::tai::TaiModule {
                name: "main".to_string(),
                description: "打印 \"Hello from Tailang\"".to_string(),
                functions: vec![],
            }],
            code_blocks: vec![],
            unresolved_items: vec![],
        }
    }

    #[test]
    fn generates_fallback_rust_main_when_no_rust_block_exists() {
        let output = CodeGenerator::new()
            .generate_rust_source(&sample_tai())
            .expect("codegen should succeed");

        assert!(output.rust_source.contains("fn tailang_main()"));
        assert!(output.rust_source.contains("println!(\"Hello from Tailang\")"));
        assert!(output.rust_source.contains("fn main()"));
    }

    #[test]
    fn preserves_rust_code_blocks() {
        let mut tai = sample_tai();
        tai.code_blocks.push(TaiCodeBlock {
            language: "rust".to_string(),
            code: "fn helper() { println!(\"helper\"); }".to_string(),
            linked_to: None,
        });

        let output = CodeGenerator::new()
            .generate_rust_source(&tai)
            .expect("codegen should succeed");

        assert!(output.rust_source.contains("fn helper()"));
    }

    #[test]
    fn detects_existing_main_function() {
        let mut tai = sample_tai();
        tai.code_blocks.push(TaiCodeBlock {
            language: "rust".to_string(),
            code: "fn main() { println!(\"custom main\"); }".to_string(),
            linked_to: None,
        });

        let output = CodeGenerator::new()
            .generate_rust_source(&tai)
            .expect("codegen should succeed");

        assert!(output.rust_source.contains("custom main"));
        assert!(!output.rust_source.contains("fn tailang_main()"));
    }

    #[test]
    fn generates_rust_from_textual_tai_source() {
        let source = r#"
.版本 3
.目标平台 视窗

.程序集 认证
.说明 "认证流程"
.程序集变量 默认次数, 整数型 = 3

.子程序 登录, 文本型
.参数 邮箱, 文本型
.局部变量 结果, 文本型 = ""
.校验 "邮箱不能为空"
.如果 邮箱 等于 ""
    .返回 "邮箱不能为空"
.如果结束
.令 结果 = 邮箱
.返回 结果
.代码 Rust
println!("hello");
.代码结束

.待定 规则, "缺少密码复杂度规则"
"#;

        let output =
            generate_rust_from_tai_source(source).expect("textual .tai codegen should succeed");
        assert!(output.rust_source.contains("mod 认证"));
        assert!(output.rust_source.contains("pub fn 默认次数_初始化() -> i64 { 3 }"));
        assert!(output.rust_source.contains("pub fn 登录(邮箱: String) -> String"));
        assert!(output.rust_source.contains("let mut 结果: String = \"\".to_string();"));
        assert!(output.rust_source.contains("let 结果 = 邮箱;"));
        assert!(output.rust_source.contains("if 邮箱 == \"\" {"));
        assert!(output.rust_source.contains("return 结果;"));
        assert!(output.rust_source.contains("println!(\"hello\");"));
    }

    #[test]
    fn lowers_native_tai_implementation_to_rust() {
        let rust = lower_implementation_to_rust(
            &TaiFunctionDecl {
                name: "登录".to_string(),
                return_type: None,
                params: vec!["用户名".to_string()],
                param_decls: vec![],
                locals: vec![],
                doc: None,
                validations: vec![],
                implementation: None,
                code_blocks: vec![],
            },
            r#"
.令 结果 = 用户名
.如果 结果 等于 ""
    .返回 "空"
.如果结束
.返回 结果
"#,
        )
        .expect("lower should succeed");

        assert!(rust.contains("let 结果 = 用户名;"));
        assert!(rust.contains("if 结果 == \"\" {"));
        assert!(rust.contains("return 结果;"));
    }
}
